overrides:
  'flatted@<=3.4.1': 3.4.2
  js-yaml: 4.1.1
  'minimatch@>=9.0.0 <9.0.7': 9.0.7
  strip-ansi: 6.0.1
  undici-types: 6.24.1
  undici: 6.24.0
  wrap-ansi: 10.0.0
  string-width: 4.2.3
  'eslint-plugin-barrel-files>oxc-resolver': 11.19.1
  'eslint-plugin-jest>@typescript-eslint/utils': 8.57.2
